apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.storeName }}
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.mariadb.dbName }}
  MYSQL_USER: {{ .Values.mariadb.user }}
  MYSQL_PASSWORD: {{ .Values.mariadb.password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword }}
